spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/jpashop
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:

  jpa:
    generate-ddl: off
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
#        format_sql: ture

logging:
  config: classpath:./log4j2/log4j2-prod.yml
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
